services:
  - type: web
    name: arabic-word-modifier
    runtime: python
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.12